### ISSUE TITLE
Question about how to select the best result

### ISSUE THREAD

**Issue by visionxyz** [KentoNishi/JTR-CVPR-2024#1]
Thank you for your great work. 
I am running this code, but I have a question. How can I get the best results? Since there are only train and test sets, what we need to do is to find the best delta from these 400 epochs? If you could answer my question, I would greatly appreciate it.

**Comment by KentoNishi** [comment]
In `logs.csv` for each training run, the last column is `best_delta_mtl`, and the second-to-last column is the current epoch's `delta_mtl`. You can simply find the checkpoint corresponding to when `best_delta_mtl == delta_mtl`. Hope that helps!
